# Generated by Django 2.2 on 2020-08-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200824_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotationchart',
            name='img',
            field=models.ImageField(upload_to='static/img', verbose_name='图片'),
        ),
    ]
