# Generated by Django 2.2 on 2020-08-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200824_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='state',
            field=models.BooleanField(default=1, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
