# Generated by Django 2.2 on 2020-08-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_loginrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Last_login_time',
            field=models.CharField(blank=True, max_length=20, verbose_name='上次登录'),
        ),
    ]
