# Generated by Django 2.2 on 2020-08-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='笔记名称')),
                ('catalog', models.TextField(verbose_name='笔记目录')),
                ('img', models.ImageField(upload_to='', verbose_name='封面')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('browse_number', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '笔记目录',
                'verbose_name_plural': '笔记目录',
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='NoteContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='内容')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Note')),
            ],
            options={
                'verbose_name': '内容',
                'verbose_name_plural': '内容',
                'db_table': 'note_content',
            },
        ),
    ]
