# Generated by Django 2.2 on 2020-08-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20200821_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(default='static/img/biji.jpg', upload_to='static/img', verbose_name='封面'),
        ),
    ]
