# Generated by Django 2.2 on 2020-08-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20200821_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='catalog',
            field=models.TextField(blank=True, default='[{"mu": "暂时没有内容", "ex": []}]', verbose_name='笔记目录'),
        ),
    ]
