# Generated by Django 2.2 on 2020-08-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='browse_number',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comment_number',
            field=models.IntegerField(default=0, verbose_name='评论量'),
        ),
    ]
