# Generated by Django 2.2 on 2020-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200820_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='introduce',
            field=models.CharField(blank=True, max_length=70, verbose_name='简介'),
        ),
    ]
