# Generated by Django 2.2 on 2020-08-28 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='书名')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('press', models.CharField(max_length=20, verbose_name='出版社')),
                ('pub_date', models.DateField(verbose_name='出版时间')),
                ('catalog', models.TextField(blank=True, verbose_name='目录')),
                ('creation_time', models.DateField(auto_now_add=True, verbose_name='入手时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='内容')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
            options={
                'verbose_name': '书籍内容',
                'verbose_name_plural': '书籍内容',
                'db_table': 'book_content',
            },
        ),
    ]
