# Generated by Django 2.2 on 2020-08-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img', verbose_name='封面'),
        ),
    ]
