# Generated by Django 2.2 on 2020-08-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontent',
            name='title',
            field=models.CharField(blank=True, max_length=30, verbose_name='章节'),
        ),
    ]
